# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/html-table/all/html-table.rbi
#
# html-table-1.7.1

class NonStandardExtensionWarning < StructuredWarnings::StandardWarning
end
class BlinkWarning < StructuredWarnings::StandardWarning
end
class ArgumentTypeError < ArgumentError
end
module HTML
end
class HTML::Table < Array
  def <<(obj); end
  def []=(index, obj); end
  def content=(arg); end
  def data=(arg); end
  def header(arg = nil); end
  def header=(arg); end
  def initialize(arg = nil, html_options = nil, &block); end
  def push(*args); end
  def self.global_end_tags=(bool); end
  def self.global_end_tags?; end
  def self.html_case; end
  def self.html_case=(arg); end
  def self.indent_level; end
  def self.indent_level=(num); end
  def to_s(formatting = nil); end
  def to_str(formatting = nil); end
  def unshift(obj); end
  include HTML::Mixin::AttributeHandler
  include HTML::Mixin::HtmlHandler
end
