# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/lint_roller/all/lint_roller.rbi
#
# lint_roller-1.1.0

module LintRoller
end
class LintRoller::About < Struct
  def description; end
  def description=(_); end
  def homepage; end
  def homepage=(_); end
  def name; end
  def name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.keyword_init?; end
  def self.members; end
  def self.new(*arg0); end
  def version; end
  def version=(_); end
end
class LintRoller::Context < Struct
  def engine; end
  def engine=(_); end
  def engine_version; end
  def engine_version=(_); end
  def rule_format; end
  def rule_format=(_); end
  def runner; end
  def runner=(_); end
  def runner_version; end
  def runner_version=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.keyword_init?; end
  def self.members; end
  def self.new(*arg0); end
  def target_ruby_version; end
  def target_ruby_version=(_); end
end
class LintRoller::Rules < Struct
  def config_format; end
  def config_format=(_); end
  def error; end
  def error=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.keyword_init?; end
  def self.members; end
  def self.new(*arg0); end
  def type; end
  def type=(_); end
  def value; end
  def value=(_); end
end
class LintRoller::Plugin
  def about; end
  def initialize(config = nil); end
  def rules(context); end
  def supported?(context); end
end
class LintRoller::Error < StandardError
end
module LintRoller::Support
end
class LintRoller::Support::MergesUpstreamMetadata
  def merge(plugin_yaml, upstream_yaml); end
end
