# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/structured_warnings/all/structured_warnings.rbi
#
# structured_warnings-0.4.0

module StructuredWarnings
  extend StructuredWarnings::ClassMethods
end
module Dynamic
  extend Dynamic::ClassMethods
end
module Dynamic::ClassMethods
  def [](key); end
  def []=(key, value); end
  def here!; end
  def let(bindings, &block); end
  def method_missing(name, *args); end
  def self.main_dynamics; end
  def undefine(*keys); end
  def variable(definition); end
  def variables; end
end
module StructuredWarnings::Kernel
  def warn(*args); end
end
class Object < BasicObject
  include StructuredWarnings::Kernel
end
module StructuredWarnings::Warning
  def warn(*args); end
end
module Warning
  extend StructuredWarnings::Warning
end
class StructuredWarnings::Warner
  def format(warning, message, options, stack); end
end
class StructuredWarnings::Base
  def backtrace; end
  def initialize(message = nil); end
  def inspect; end
  def message; end
  def set_backtrace(backtrace); end
  def to_s; end
  def to_str; end
  extend StructuredWarnings::Base::ClassMethods
end
module StructuredWarnings::Base::ClassMethods
  def active?; end
  def disable; end
  def enable; end
end
class StructuredWarnings::StandardWarning < StructuredWarnings::Base
end
class StructuredWarnings::DeprecationWarning < StructuredWarnings::Base
end
class StructuredWarnings::DeprecatedMethodWarning < StructuredWarnings::DeprecationWarning
end
class StructuredWarnings::DeprecatedSignatureWarning < StructuredWarnings::DeprecationWarning
end
class StructuredWarnings::BuiltInWarning < StructuredWarnings::Base
end
module StructuredWarnings::ClassMethods
  def disabled_warnings; end
  def disabled_warnings=(new_disabled_warnings); end
  def warner; end
  def warner=(new_warner); end
  def with_disabled_warnings(disabled_warnings); end
  def with_warner(warner); end
end
