# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/unicode-display_width/all/unicode-display_width.rbi
#
# unicode-display_width-3.2.0

module Unicode
end
class Unicode::DisplayWidth
  def get_config(**kwargs); end
  def initialize(ambiguous: nil, overwrite: nil, emoji: nil); end
  def of(string, **kwargs); end
  def self.decompress_index(index, level); end
  def self.emoji_width(string, mode = nil, ambiguous = nil); end
  def self.emoji_width_via_possible(string, emoji_set_regex, strict_eaw = nil, ambiguous = nil); end
  def self.normalize_options(string, ambiguous = nil, overwrite = nil, old_options = nil, **options); end
  def self.of(string, ambiguous = nil, overwrite = nil, old_options = nil, **options); end
  def self.width_ascii(string); end
  def self.width_custom(string, overwrite); end
end
module Unicode::DisplayWidth::EmojiSupport
  def self._recommended; end
  def self.recommended; end
end
