# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/unicode-emoji/all/unicode-emoji.rbi
#
# unicode-emoji-4.2.0

module Unicode
end
module Unicode::Emoji
  def self.get_codepoint_value(char); end
  def self.list(key = nil, sub_key = nil); end
  def self.properties(char); end
end
