require: rubocop-rspec

RSpec/MultipleExpectations:
  Max: 4
RSpec/ContextWording:
  Enabled: false
RSpec/FilePath:
  SpecSuffixOnly: true
RSpec/InstanceVariable:
  Enabled: false
RSpec/BeforeAfterAll:
  Enabled: false
RSpec/ExampleLength:
  Max: 10

AllCops:
  NewCops: enable
  Exclude:
    - Gemfile
    - html-table.gemspec
    - Rakefile
    - examples/*.rb
Lint/AssignmentInCondition:
  Enabled: false
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/CaseIndentation:
  IndentOneStep: true
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  PreferredName: 'err'
Naming/FileName:
  Exclude:
    - 'lib/html-table.rb'

Lint/EmptyBlock:
  Exclude:
    - 'spec/*.rb'
